---
title: "Day 3"
author: "Victoria Cutler"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(palmerpenguins)
```

### `if` statements

```{r}
burrito <- 1

if (burrito > 2) {
  print("i love burritos")
} ## command shift return runs all code
```

```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "r") ## does each element in my_ships contain the letter r? this is case sensitive! you could convert to lowercase first to not worry about that

# Example of string detect:

phrase <- "I love burritos"

if(str_detect(phrase, "love")) {
  print("I am a burrito fan")
}
```

```{r}
tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine") # essentially doing a four loop if else statement for u

# Use %in% operator to check for multiple positive matches instead of above method with | symbol
tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Endor", "Naboo")) # essentially the same line as above with the "or" operator, that's just more lengthy
```

#### `if-else` statement

```{r}
pika <- 89.1

if(pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}
```

```{r}
marmot <- 2.8

if (marmot <0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}

```

### `group_by() %>% summarize()`

```{r}
penguins |> 
  group_by(species, island) |> 
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            sd_bill_length = sd(bill_length_mm, na.rm = TRUE),
            sample_size = n())

# find the mean and standard deviation of character height in starwars grouped by homeworld

starwars_groupby = starwars |> 
  group_by(homeworld) |> 
  summarize(mean = mean(height, na.rm =TRUE),
            st_dev = sd(height, na.rm = TRUE))

starwars_groupby

# find the maximum and minimum flipper length, and sample size for each species of penguins 

penguins_groupby = penguins |> 
  group_by(species) |> 
  summarize(max_flipper_length = max(flipper_length_mm, na.rm = TRUE),
            min_flipper_length = min(flipper_length_mm, na.rm = TRUE),
            sample_size = n())
penguins_groupby

penguins |> 
  group_by(species) |> 
  summarize(across(where(is.numeric), c(mean, sd), na.rm = TRUE))
```

```{r}
tree_height <- c(1, 2, 6, 10, 14, 20)

for (i in seq_along(tree_height)) {
  val = tree_height[i] + tree_height[i+1]
  print(val)
}
```

```{r}

animal_ages <- vector(mode = "numeric", length = length(species))

species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")

age_human_years <- c(3, 8, 4, 6, 12, 18)

for (i in seq(species)) {
  if (species[i] == "dog") {
    animal_age <- age_human_years[i] * 7
  } else if (species[i] == "elephant") {
    animal_age <- age_human_years[i] * 0.88
  } else if (species[i] == "goat") {
    animal_age <- age_human_years[i] * 4.7
  } 
  print(animal_age)
}

for (i in seq(species)) {
  if (species[i] == "dog") {
    animal_age <- age_human_years[i] * 7
  } else if (species[i] == "elephant") {
    animal_age <- age_human_years[i] * 0.88
  } else if (species[i] == "goat") {
    animal_age <- age_human_years[i] * 4.7
  } 
  animal_ages[i] <- animal_age
}
```

```{r}
mean_mtcars <- vector(mode = "numeric", length = ncol(mtcars))

for (i in seq_along(mtcars)) {
  mean_val <- mean(mtcars[[i]], na.rm = TRUE)
  mean_mtcars[i] <- mean_val
}

mean_mtcars
```

adding syntactic sugar (apply, across, map_df

```{r}
apply(X = mtcars, MARGIN = 2, FUN = mean)
apply(mtcars, 2, mean)
```

```{r}
map(.x = mtcars, .f = mean)

map_df(mtcars, mean)
```
